// Learning objectives per worksheet SET (one objective per chapter x series
// cell). A "set" is the parts that share a code stem, e.g. SG101A1 + SG101A2,
// which together cover one objective.
//
// Keyed by SET CODE = an item code with its trailing part-number stripped:
//   SG101A1 / SG101A2  ->  "SG101A"
//   SG101R1 / SG101R2  ->  "SG101R"
//
// This file is hand-edited and kept separate from the auto-generated
// mc-drive-checktables.ts so objectives survive regeneration. Drop the real
// objectives in here as they arrive; sets with no entry just render without
// one.
//
// Coverage so far:
//   - CA Level 1 & 2: REAL objectives, transcribed from the "CA Learning Plan
//     FullList" PDFs (every NA/MG/ST/PS set code in both books).
//   - SG Level 1: PLACEHOLDER samples only, pending the authored objectives.

export const coursewareObjectives: Record<string, string> = {
  // --- SG Level 1 (PLACEHOLDER — replace when authored) -------------------
  // Ch 1 — Numbers to 10
  SG101A: "Counting and recognising numbers from 1 to 10",
  SG101B: "Reading and writing numbers in words and figures up to 10",
  SG101C: "Comparing two groups to find which has more or fewer",
  SG101D: "Ordering numbers from 1 to 10 and finding what comes before and after",
  SG101R: "Revision of counting, reading and comparing numbers to 10",
  // Ch 2 — One to One Correspondence
  SG102A: "Matching objects one to one to compare quantities",
  SG102B: "Deciding whether two sets are equal by pairing items",
  SG102R: "Revision of one-to-one matching",
  // Ch 3 — Number Bonds
  SG103A: "Splitting numbers up to 10 into two parts",
  SG103B: "Finding the missing part of a number bond",
  SG103C: "Writing the number bonds that make a given number",
  SG103R: "Revision of number bonds within 10",
  // Ch 10 — Shapes and Patterns
  SG110A: "Identifying circles, triangles, rectangles and squares",
  SG110B: "Sorting shapes by their number of sides and corners",
  SG110C: "Continuing and completing simple repeating patterns",
  SG110R: "Revision of shapes and patterns",
  // Ch 13 — Numbers to 20
  SG113A: "Counting and writing numbers from 11 to 20",
  SG113B: "Showing teen numbers as a ten and some ones",
  SG113C: "Comparing and ordering numbers up to 20",
  SG113D: "Finding the number that is one more or one less within 20",
  SG113R: "Revision of numbers to 20",
  // --- CA Level 1 & 2 (REAL — from CA Learning Plan FullList PDFs) --------
  "MG101A": "Identifying circles, triangles, rectangles and squares",
  "MG101B": "Grouping shapes",
  "MG101C": "Recognising shapes around us",
  "MG101R": "Consolidation of shapes and patterns",
  "MG102A": "Making patterns with different shapes",
  "MG102B": "Making patterns with shapes of different sizes",
  "MG102C": "Making patterns with shapes of different colours",
  "MG102D": "Making patterns with shapes of different orientations",
  "MG102R": "Consolidation of making patterns with shapes",
  "MG103A": "Length",
  "MG103B": "Comparing lengths",
  "MG103C": "Measuring length using non-standard units",
  "MG103D": "Measuring length in units",
  "MG103R": "Consolidation of length",
  "MG104A": "Hour",
  "MG104B": "Telling time to the hour",
  "MG104C": "Telling time to the half hour",
  "MG104D": "More about time",
  "MG104R": "Consolidation of time",
  "NA101A": "Counting numbers 0 to 5",
  "NA101B": "Counting numbers 6 to 10",
  "NA101C": "Comparing numbers",
  "NA101D": "Comparing and arranging numbers with symbols",
  "NA101E": "Making number patterns",
  "NA101R": "Consolidation of numbers to 10",
  "NA102A": "Comparing two groups of objects with one-to-one correspondence",
  "NA102B": "Comparing two groups of objects with one-to-one correspondence",
  "NA102R": "Consolidation of one-to-one correspondence",
  "NA103A": "Number bonds up to 5 with five-frame",
  "NA103B": "Number bonds up to 5 with five-frame",
  "NA103C": "Number bonds up to 10 with ten-frame",
  "NA103R": "Consolidation of number bonds",
  "NA104A": "Adding with number bonds",
  "NA104B": "Adding within 10 by counting on",
  "NA104C": "Addition fact",
  "NA104D": "Addition of three 1-digit numbers",
  "NA104E": "Missing addends",
  "NA104F": "Addition in making 10",
  "NA104R": "Consolidation of addition within 10",
  "NA105A": "Subtracting by taking away",
  "NA105B": "Subtraction within 5 by counting back",
  "NA105C": "Subtracting 6 to 9 by counting on",
  "NA105D": "Subtracting with number bonds",
  "NA105E": "Find the missing minuend and subtrahend",
  "NA105F": "Three numbers subtraction",
  "NA105R": "Consolidation of subtraction within 10",
  "NA106A": "Zero",
  "NA107A": "Relationship between addition and subtraction",
  "NA107B": "Making fact families",
  "NA107R": "Consolidation of relationship between addition and subtraction",
  "NA108A": "Ordinal numbers and position words",
  "NA108B": "Ordinal numbers and position words",
  "NA108R": "Consolidation of ordinal numbers and position words",
  "NA109A": "Counting numbers 11 to 15 with ten frame",
  "NA109B": "Counting numbers 16 to 20 with ten frame",
  "NA109C": "Comparing numbers",
  "NA109D": "Making number patterns",
  "NA109E": "Making number patterns",
  "NA109R": "Consolidation of numbers to 20 through mixed practice (1)",
  "NA110A": "Adding of 1-5 by counting on",
  "NA110B": "Doubling method on addition",
  "NA110C": "Adding by making 10",
  "NA110D": "Adding by making 10",
  "NA110E": "Find the missing addend",
  "NA110F": "Three numbers addition",
  "NA110G": "Consolidation of addition within 20 (1)",
  "NA110H": "Consolidation of addition within 20 (2)",
  "NA110I": "Consolidation of addition within 20 (3)",
  "NA111A": "Subtracting by counting back",
  "NA111B": "Subtracting from 10",
  "NA111C": "Three numbers subtraction by counting back",
  "NA111D": "Three numbers subtraction from 10",
  "NA111E": "Find the missing subtrahend",
  "NA111F": "Find the missing minuend",
  "NA111G": "Consolidation of subtraction within 20 (1)",
  "NA111H": "Consolidation of subtraction within 20 (2)",
  "NA111I": "Consolidation of subtraction within 20 (3)",
  "NA112A": "Counting numbers to 40",
  "NA112B": "Place value",
  "NA112C": "Comparing numbers",
  "NA112D": "Comparing numbers",
  "NA112E": "Making number patterns",
  "NA112F": "Consolidation of numbers to 40 through mixed practice (1)",
  "NA112G": "Consolidation of numbers to 40 through mixed practice (2)",
  "NA112H": "Consolidation of numbers to 40 through mixed practice (3)",
  "NA113A": "Addition without regrouping (2 digits add 1 digit)",
  "NA113B": "Addition without regrouping (2 digits add 2 digits)",
  "NA113C": "Addition with regrouping (2 digits add 1 digit)",
  "NA113D": "Addition with regrouping (2 digits add 2 digits)",
  "NA113E": "Addition of three numbers (1 digit)",
  "NA113F": "Addition of three numbers using algorithm",
  "NA113G": "Find the missing addend in algorithm",
  "NA113H": "Find the missing addend in algorithm",
  "NA113I": "Consolidation of addition within 40 (1)",
  "NA113J": "Consolidation of addition within 40 (2)",
  "NA113K": "Consolidation of addition within 40 (3)",
  "NA114A": "Subtraction without regrouping",
  "NA114B": "Subtraction without regrouping",
  "NA114C": "Subtraction with regrouping",
  "NA114D": "Subtraction with regrouping",
  "NA114E": "Three numbers subtraction",
  "NA114F": "Find the missing numbers",
  "NA114G": "Consolidation of subtraction within 40 (1)",
  "NA114H": "Consolidation of subtraction within 40 (2)",
  "NA115A": "Multiplying by adding the same number",
  "NA115B": "Making multiplication stories",
  "NA115C": "More about multiplication",
  "NA115D": "More about multiplication",
  "NA116A": "Sharing a number of objects equally",
  "NA116B": "Finding the number of equal groups",
  "NA116C": "Consolidation of division",
  "NA116D": "More on division",
  "NA117A": "Counting numbers to 100",
  "NA117B": "Place values",
  "NA117C": "Comparing numbers",
  "NA117D": "Making number patterns",
  "NA117E": "Consolidation of numbers to 100 (1)",
  "NA117F": "Consolidation of numbers to 100 (2)",
  "NA118A": "Addition without regrouping",
  "NA118B": "Addition without regrouping",
  "NA118C": "Addition with regrouping in algorithm",
  "NA118D": "Addition with regrouping by place value",
  "NA118E": "Three numbers addition",
  "NA118F": "Consolidation of addition within 100 (1)",
  "NA118G": "Consolidation of addition within 100 (2)",
  "NA119A": "Subtraction without regrouping",
  "NA119B": "Subtraction without regrouping",
  "NA119C": "Subtraction without regrouping",
  "NA119D": "Subtraction with regrouping in algorithm",
  "NA119E": "Subtraction with regrouping by place value",
  "NA119F": "Find the missing number",
  "NA119G": "Three numbers subtraction",
  "NA119H": "Consolidation of subtraction within 100 (1)",
  "NA119I": "Consolidation of subtraction within 100 (2)",
  "NA120A": "Getting to know our money",
  "NA120B": "Telling the amount of money",
  "NA120C": "Telling the amount of money",
  "NA120D": "Exchanging coins and notes",
  "NA120R": "Consolidation of money concept",
  "NA121A": "Adding and subtracting money in cents",
  "NA121B": "Adding and subtracting money in cents",
  "NA121C": "Adding and subtracting money in dollars",
  "NA121D": "Adding and subtracting money in dollars",
  "NA121R": "Consolidation of adding and subtracting money",
  "ST101A": "Understanding vertical picture graphs",
  "ST101B": "Understanding vertical picture graphs",
  "ST101C": "Understanding horizontal picture graphs",
  "ST101D": "Making vertical picture graphs",
  "ST101E": "Making horizontal picture graphs",
  "PS.NA104A": "Word problems of addition within 10 by counting on",
  "PS.NA104B": "Word problems of addition within 10 with number bonds",
  "PS.NA104C": "Word problems of addition within 10 involving 'more than'",
  "PS.NA104D": "Word problems of addition within 10 involving 'fewer than'",
  "PS.NA104E": "Word problem revision of addition within 10",
  "PS.NA104F": "Word problem revision of addition within 10",
  "PS.NA105A": "Word problems of subtraction within 10 by taking away",
  "PS.NA105B": "Word problems of subtraction within 10 by counting back",
  "PS.NA105C": "Word problems of subtraction within 10 by counting on",
  "PS.NA105D": "Word problems of subtraction within 10 with number bonds",
  "PS.NA105E": "Word problems of subtraction within 10 involving 'more than'",
  "PS.NA105F": "Word problems of subtraction within 10 involving 'fewer than'",
  "PS.NA105G": "Word problem revision of subtraction within 10",
  "PS.NA105H": "Word problem revision of subtraction within 10",
  "PS.NA107A": "Word problems of addition and subtraction within 10",
  "PS.NA107B": "Word problems of addition and subtraction within 10",
  "PS.NA107C": "Word problems of addition and subtraction within 10",
  "PS.NA110A": "Word problems of addition within 20 by counting on",
  "PS.NA110B": "Word problems of addition within 20 by making 10",
  "PS.NA110C": "Word problem revision of addition within 20",
  "PS.NA110D": "Word problem revision of addition within 20",
  "PS.NA111A": "Word problems of subtraction within 20 by counting back",
  "PS.NA111B": "Word problems of subtraction within 20 by subtracting from 10",
  "PS.NA111C": "Word problem revision of subtraction within 20",
  "PS.NA111D": "Word problem revision of subtraction within 20",
  "PS.NA111E": "Word problems of addition and subtraction within 20",
  "PS.NA111F": "Word problems of addition and subtraction within 20",
  "PS.NA111G": "Word problems of addition and subtraction within 20",
  "PS.NA113A": "Word problems of addition within 40 without regrouping",
  "PS.NA113B": "Word problems of addition within 40 without regrouping",
  "PS.NA113C": "Word problems of addition within 40 with regrouping",
  "PS.NA113D": "Word problems of addition within 40 involving 3 numbers",
  "PS.NA113E": "Word problems of addition within 40 involving 3 numbers",
  "PS.NA113F": "Word problem revision of addition within 40",
  "PS.NA113G": "Word problem revision of addition within 40",
  "PS.NA114A": "Word problems of subtraction within 40 without regrouping",
  "PS.NA114B": "Word problems of subtraction within 40 without regrouping",
  "PS.NA114C": "Word problems of subtraction within 40 with regrouping",
  "PS.NA114D": "Word problem revision of subtraction within 40",
  "PS.NA114E": "Word problem revision of subtraction within 40",
  "PS.NA114F": "Word problems of addition and subtraction within 40",
  "PS.NA114G": "Word problems of addition and subtraction within 40",
  "PS.NA114H": "Word problems of addition and subtraction within 40",
  "PS.NA115A": "Word problems of multiplication within 40 by adding the same number",
  "PS.NA115B": "Word problems of multiplication within 40",
  "PS.NA115C": "Word problem revision of multiplication within 40",
  "PS.NA115D": "Word problem revision of multiplication within 40",
  "PS.NA116A": "Word problems of division within 20 by sharing equally",
  "PS.NA116B": "Word problems of division within 20 by finding the number of equal groups",
  "PS.NA116C": "Word problem revision of division within 20",
  "PS.NA116D": "Word problem revision of division within 20",
  "PS.NA118A": "Word problems of addition within 100 without regrouping",
  "PS.NA118B": "Word problems of addition within 100 with regrouping",
  "PS.NA118C": "Word problem revision of addition within 100",
  "PS.NA119A": "Word problems of subtraction within 100 without regrouping",
  "PS.NA119B": "Word problems of subtraction within 100 with regrouping",
  "PS.NA119C": "Word problem revision of subtraction within 100",
  "PS.NA119D": "Word problems of addition and subtraction within 100",
  "PS.NA121A": "Word problems of addition and subtraction of money in cents",
  "PS.NA121B": "Word problems of addition and subtraction of money in dollars",
  "PS.NA121C": "Word problem revision of addition and subtraction of money",
  "MG201A": "Measuring in metres (m)",
  "MG201B": "Comparing and ordering length in metres",
  "MG201C": "Measuring in centimetres (cm)",
  "MG201D": "Comparing and ordering length in centimetres",
  "MG201E": "Choosing suitable units of length",
  "MG201R": "Consolidation of metres and centimetres concept",
  "MG202A": "Comparing mass directly",
  "MG202B": "Measuring and comparing mass using non-standard units",
  "MG202R": "Consolidation of mass concept",
  "MG203A": "Measuring in kilograms",
  "MG203B": "Measuring in grams",
  "MG203C": "Measuring and comparing mass in grams or kilograms",
  "MG203D": "Choosing suitable unit of mass",
  "MG203R": "Consolidation of grams and kilograms",
  "MG204A": "Semicircles and quarter circles",
  "MG204B": "Combining shapes to make a figure",
  "MG204C": "Drawing figures on dot grids or square grids",
  "MG204R": "Consolidation of shapes and two-dimensional figures",
  "MG205A": "Identifying solids",
  "MG205B": "Grouping solids",
  "MG205C": "Building figure with solids",
  "MG205R": "Consolidation of solids and three-dimensional figures",
  "MG206A": "Making patterns with shapes",
  "MG206B": "Making patterns with shapes",
  "MG206C": "Making patterns with solids",
  "MG206R": "Consolidation of making patterns",
  "MG207A": "Reading and writing time to 5 minutes",
  "MG207B": "Morning (a.m.) and afternoon (p.m.)",
  "MG207C": "Time taken in hours and minutes",
  "MG207R": "Consolidation of time concept",
  "MG208A": "Comparing volumes directly",
  "MG208B": "Comparing volumes using containers",
  "MG208C": "Comparing volumes using a litre of liquid",
  "MG208R": "Consolidation of volume concept",
  "NA201A": "Counting to 1000",
  "NA201B": "Place values",
  "NA201C": "Comparing numbers",
  "NA201D": "Making number patterns",
  "NA201E": "Even and odd numbers",
  "NA201R": "Consolidation of numbers to 1000",
  "NA202A": "Addition without regrouping",
  "NA202B": "Addition with regrouping once",
  "NA202C": "Algorithm addition, add the numbers with an algorithm",
  "NA202D": "Addition with regrouping twice",
  "NA202E": "Finding missing numbers in an algorithm",
  "NA202R": "Consolidation of addition within 1000",
  "NA203A": "Subtraction without regrouping",
  "NA203B": "Subtraction with regrouping once",
  "NA203C": "Algorithm subtraction",
  "NA203D": "Subtraction with regrouping twice",
  "NA203E": "Finding missing numbers in an algorithm",
  "NA203R": "Consolidation of subtraction within 1000",
  "NA204A": "Revision on multiplication",
  "NA204B": "Review of dividing",
  "NA204C": "Review of grouping",
  "NA204R": "Consolidation of multiplication & division",
  "NA205A": "Multiplication table of 2",
  "NA205B": "Multiplication table of 5",
  "NA205C": "Multiplication table of 10",
  "NA205D": "Multiplication table of 3",
  "NA205E": "Multiplication table of 4",
  "NA205R": "Consolidation of multiplication 2, 3, 4, 5 and 10",
  "NA206A": "Multiplying numbers in any order",
  "NA206B": "Dividing using multiplication facts",
  "NA206C": "Multiplying numbers in any order",
  "NA207A": "Counting dollars and cents",
  "NA207B": "Changing dollars and cents",
  "NA207C": "Comparing amount of money",
  "NA207R": "Consolidation of money concept",
  "NA208A": "Understanding fractions",
  "NA208B": "Understanding the concept of fractions as parts of a whole",
  "NA208C": "More fractions",
  "NA208R": "Consolidation of fraction concept",
  "NA209A": "Comparing fractions with the same denominator",
  "NA209B": "Comparing fractions with the same numerator",
  "NA209C": "Comparing and ordering fractions",
  "NA209R": "Consolidation of comparing and ordering fractions",
  "NA210A": "Addition of like fractions",
  "NA210B": "Subtraction of like fractions",
  "NA210R": "Consolidation of addition and subtraction of like fractions",
  "ST201A": "Understanding picture graphs",
  "ST201B": "Understanding picture graphs",
  "ST201C": "Making picture graphs",
  "ST201D": "Making picture graphs",
  "ST201R": "More on picture graphs",
  "PS.MG201A": "Word problems of addition of length",
  "PS.MG201B": "Word problems of subtraction of length",
  "PS.MG201C": "Word problem revision on addition and subtraction of length",
  "PS.MG201D": "Word problems of multiplication of length",
  "PS.MG201E": "Word problems of division of length",
  "PS.MG201F": "Word problem revision on multiplication and division of length",
  "PS.MG203A": "Word problems of simple addition and subtraction of mass",
  "PS.MG203B": "Word problems of addition and subtraction of mass",
  "PS.MG203C": "Word problems of multiplication and division of mass",
  "PS.MG203D": "Word problem revision on mass",
  "PS.MG208A": "Word problems of simple addition and subtraction of volumes",
  "PS.MG208B": "Word problems of addition and subtraction of volumes",
  "PS.MG208C": "Word problems of multiplication and division of volumes",
  "PS.MG208D": "Word problem revision on volume",
  "PS.NA202A": "Word problems of addition within 1000 using part-whole",
  "PS.NA202B": "Word problems of addition within 1000 by adding on and taking away sets",
  "PS.NA202C": "Word problems of addition within 1000 by comparing two sets",
  "PS.NA203A": "Word problems of subtraction within 1000 using part-whole",
  "PS.NA203B": "Word problems of subtraction within 1000 by adding on and taking away sets",
  "PS.NA203C": "Word problems of subtraction within 1000 by comparing two sets",
  "PS.NA203D": "Word problems of subtraction within 1000 by comparing two sets",
  "PS.NA203E": "Word problems of addition and subtraction within 1000 using part-whole",
  "PS.NA203F": "Word problems of addition and subtraction within 1000 by adding on and taking away sets",
  "PS.NA203G": "Word problems of addition and subtraction within 1000 by comparing two sets",
  "PS.NA203H": "Word problem revision of addition and subtraction within 1000",
  "PS.NA203I": "2-part word problems with comparison I",
  "PS.NA203J": "2-part word problems with comparison II",
  "PS.NA203K": "2-part word problems (Part and Whole Concept)",
  "PS.NA203L": "2-part word problems of addition and subtraction within 1000",
  "PS.NA203M": "Challenge problems on addition and subtraction within 1000",
  "PS.NA205A": "Word problems of multiplication using multiplication tables 2, 3, 4, 5 and 10",
  "PS.NA205B": "Word problems of multiplication by using commutative property of multiplication",
  "PS.NA205C": "Word problems of multiplication involving 'as many as'",
  "PS.NA205D": "Word problem revision on multiplication",
  "PS.NA206A": "Word problems of division by sharing equally using multiplication tables 2, 3, 4, 5 and 10",
  "PS.NA206B": "Word problems of division by finding the number of equal groups using the multiplication tables 2, 3, 4, 5 and 10",
  "PS.NA206C": "Challenging word problems of division",
  "PS.NA206D": "Word problem revision on division",
  "PS.NA207A": "Word problems of simple addition and subtraction of money",
  "PS.NA207B": "Word problems of addition and subtraction of money",
  "PS.NA207C": "Word problems of multiplication and division of money",
  "PS.NA207D": "Word problem revision on money",
  "PS.NA210A": "Word problems of addition of like fractions",
  "PS.NA210B": "Word problems of subtraction of like fractions",
  "PS.NA210C": "Word problem revision on fractions",
};

/** Strip the trailing part-number from an item code to get its set code.
 *  "SG101A1" -> "SG101A", "SG101R2" -> "SG101R". */
export function setCodeFromItemCode(code: string): string {
  return code.replace(/\d+$/, "");
}

/** Look up the objective for a single item via its set code. This is the only
 *  resolution path: a cell can hold several sets (the merged PS series packs a
 *  chapter's PS.A/PS.B/... sets into one cell), so objectives are always
 *  derived per item, never stored per cell. */
export function objectiveForItemCode(code: string): string | undefined {
  return coursewareObjectives[setCodeFromItemCode(code)];
}
