steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-east2-docker.pkg.dev/csm-database-project/tutoring-backend/tutoring-backend:latest'
      - '.'
images:
  - 'asia-east2-docker.pkg.dev/csm-database-project/tutoring-backend/tutoring-backend:latest'
timeout: '1200s'
