-- Migration 084: Create primary_prospects table for P6-to-secondary student tracking
CREATE TABLE primary_prospects (
    id INT AUTO_INCREMENT PRIMARY KEY,
    year INT NOT NULL,
    source_branch VARCHAR(20) NOT NULL,
    primary_student_id VARCHAR(50),
    student_name VARCHAR(255) NOT NULL,
    school VARCHAR(255),
    grade VARCHAR(20),
    tutor_name VARCHAR(255),
    phone_1 VARCHAR(20),
    phone_1_relation VARCHAR(20),
    phone_2 VARCHAR(20),
    phone_2_relation VARCHAR(20),
    wechat_id VARCHAR(100),
    tutor_remark TEXT,
    wants_summer VARCHAR(20) DEFAULT 'Considering',
    wants_regular VARCHAR(20) DEFAULT 'Considering',
    preferred_branches JSON,
    preferred_time_note TEXT,
    preferred_tutor_note TEXT,
    sibling_info TEXT,
    outreach_status VARCHAR(30) NOT NULL DEFAULT 'Not Started',
    contact_notes TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'New',
    summer_application_id INT,
    submitted_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    edit_history JSON,
    FOREIGN KEY (summer_application_id) REFERENCES summer_applications(id),
    INDEX idx_prospect_year_branch (year, source_branch),
    INDEX idx_prospect_phone1 (phone_1),
    INDEX idx_prospect_phone2 (phone_2),
    INDEX idx_prospect_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
