-- Migration 164: school alias table for canonical feeder-school grouping.
-- Maps every folded spelling of a school name seen on applications to the staff
-- school code vocabulary the students table already uses. The mapping was
-- reviewed and approved row by row on 2026-08-19. Raw spellings on
-- applications are never modified. This table only adds a grouping key.
--
-- Target grammar, applied by webapp/backend/utils/school_alias.py:
--   CODE            the spelling always means that school
--   FAM|stream      Chinese/English-sectioned school. The application's
--                   lang_stream picks the section (C -> FAM-C, E or Int ->
--                   FAM-E, missing -> bare FAM)
--   CODE|int:OTHER  Int stream redirects to the international section, any
--                   other stream gives the base code

CREATE TABLE IF NOT EXISTS school_aliases (
    alias_key VARCHAR(255) NOT NULL PRIMARY KEY,
    target VARCHAR(64) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT IGNORE INTO school_aliases (alias_key, target) VALUES
('粵華中學', 'DBYW|stream'),
('慈幼中學', 'IS'),
('培正中學', 'PCMS'),
('聖羅撒英文中學', 'SRL-E'),
('聖羅撒', 'SRL|stream'),
('聖羅撒女子中學', 'SRL|stream'),
('tis', 'TIS'),
('嘉諾撒聖心英文中學', 'SHCC-E'),
('澳門培正中學', 'PCMS'),
('聖羅撒女子中學中文部', 'SRL-C'),
('培道中學', 'PTMS'),
('培正', 'PCMS|int:PCMS-CO'),
('濠江英才', 'HKMS-PS'),
('聖心', 'SHCC|stream'),
('粵華', 'DBYW|stream'),
('永援中學', 'PHC|stream'),
('陳瑞祺永援中學', 'PHC|stream'),
('勞校中學', 'LHS'),
('聖保祿', 'SPS'),
('永援', 'PHC|stream'),
('慈幼', 'IS'),
('聖心英文中學', 'SHCC-E'),
('嘉諾撒聖心中學', 'SHCC-C'),
('鏡平學校', 'KPS'),
('蔡高中學', 'CKS'),
('shcces', 'SHCC-E'),
('聖心中學', 'SHCC|stream'),
('化地瑪聖母女子學校', 'FGS'),
('菜農子弟學校', 'CNS'),
('培道', 'PTMS'),
('濠江中學', 'HKMS'),
('培華中學', 'PVMS'),
('教業中學', 'KYS|int:KYIS'),
('鏡平中學', 'KPS'),
('聖若瑟六校', 'CDSJ6|stream'),
('rosa', 'SRL-E'),
('嶺南中學', '嶺南中學'),
('教業', 'KYS|int:KYIS'),
('路環培正', 'PCMS-CO'),
('澳大附小', 'ASUM'),
('macau anglican college', 'MAC'),
('勞校', 'LHS'),
('school of the nations', 'SON'),
('澳門培道中學', 'PTMS'),
('培正中學路環校部', 'PCMS-CO'),
('海星中學', 'EM'),
('santa rosa', 'SRL-E'),
('化地瑪', 'FGS'),
('澳門葡文學校', 'EPM'),
('鮑思高粵華小學', 'DBYW|stream'),
('聖若瑟三校', 'CDSJ3'),
('is', 'IS'),
('dbyw-c', 'DBYW-C'),
('利瑪竇中學', 'CMR'),
('英才', 'HKMS-PS'),
('聖若瑟教區中學第六校', 'CDSJ6|stream'),
('聖若瑟二校', 'CDSJ2-E'),
('聖若瑟教區中學第五校', 'CDSJ5-E'),
('epm', 'EPM'),
('srl', 'SRL|stream'),
('教業國際', 'KYIS'),
('santa rosa de lima', 'SRL-E'),
('pui ching', 'PCMS|int:PCMS-CO'),
('培正路環', 'PCMS-CO'),
('聖保祿學校', 'SPS'),
('聖羅撒中文部', 'SRL-C'),
('三育中學', 'SYMS'),
('聖若瑟3校', 'CDSJ3'),
('聖瑪大肋納學校', '聖瑪大肋納學校'),
('路環培正中學', 'PCMS-CO'),
('son', 'SON'),
('澳門大學附屬應用學校', 'ASUM'),
('鄭觀應公立學校', '鄭觀應'),
('澳門三育中學', 'SYMS'),
('聖若瑟', 'CDSJ?|stream'),
('澳門培正', 'PCMS'),
('聖六', 'CDSJ6|stream'),
('shcc', 'SHCC|stream'),
('粤華中學', 'DBYW-C'),
('yuet wah college', 'DBYW-E'),
('澳門嘉諾撒聖心英文中學', 'SHCC-E'),
('hkms-ps', 'HKMS-PS'),
('ism', 'IS'),
('東南學校', 'TNS'),
('青洲中學', '青洲'),
('pui ching middle school (coloane campus)', 'PCMS-CO'),
('三育', 'SYMS'),
('領南', '嶺南中學'),
('聖若瑟教區中學三校', 'CDSJ3'),
('聖羅撒女子中學英文部', 'SRL|stream'),
('培正中學（路環校部）', 'PCMS-CO'),
('yw', 'DBYW-C'),
('聖羅撒中學', 'SRL-E'),
('srlc', 'SRL-C'),
('澳門聖保祿中學', 'SPS'),
('聖公會蔡高中學', 'CKS'),
('培正國際', 'PCMS-CO'),
('利瑪竇', 'CMR'),
('聖若瑟2校', 'CDSJ2-E'),
('聖羅撒女子英文中學', 'SRL-E'),
('東南學校(中學部)', 'TNS'),
('浸信', '浸信'),
('澳门培正中学', 'PCMS'),
('澳坊中學', 'FCS'),
('氹仔坊眾中學', 'FCT'),
('santa rosa de lima english secondary', 'SRL-E'),
('聖約瑟教區中學第五校', 'CDSJ5-C'),
('同善堂中學', '同善堂'),
('圣罗撒', 'SRL-C'),
('聖若瑟五校', 'CDSJ5|stream'),
('教業中學國際部', 'KYIS'),
('澳門浸信', '浸信'),
('澳門國際學校', 'TIS'),
('海外', '海外'),
('培正路环', 'PCMS-CO'),
('聯國學校', 'SON'),
('聖若瑟教區中學第二校', 'CDSJ2-E'),
('dbyw-e', 'DBYW-E'),
('shcc-e', 'SHCC-E'),
('cdsj2', 'CDSJ2-E'),
('cmr', 'CMR'),
('asum', 'ASUM'),
('sps', 'SPS'),
('澳大附屬', 'ASUM'),
('氹仔英才', 'HKMS-PS'),
('澳門', 'TIS'),
('macau pui ching middle school', 'PCMS'),
('粵華中學英文部', 'DBYW-E'),
('cdsj5', 'CDSJ5|stream'),
('hou kong', 'HKMS'),
('濠江中学', 'HKMS'),
('澳門聖羅撒女子中學中文部', 'SRL-C'),
('santa rosa de lima english secondary school', 'SRL-E'),
('培正國際部', 'PCMS-CO'),
('聖若瑟教區第五校', 'CDSJ5-C'),
('msy', 'SYMS'),
('聖若瑟英文部二校', 'CDSJ2-E'),
('pui ching middle school', 'PCMS'),
('圣罗撒英文部', 'SRL-E'),
('聖若瑟6校', 'CDSJ6-E'),
('澳門坊眾學校', 'FCS'),
('cdsj3', 'CDSJ3'),
('srl-e', 'SRL-E'),
('蔡高中学', 'CKS'),
('srle', 'SRL-E'),
('cdsj 6', 'CDSJ6-E'),
('教業國際部', 'KYIS'),
('聖若瑟六校英文部', 'CDSJ6-E'),
('傳承國際學校', 'GIS'),
('濠江中學附屬英才學校', 'HKMS-PS'),
('聖羅撒女子英文部', 'SRL-E'),
('sam yuk middle school', 'SYMS'),
('粵華中学', 'DBYW-C'),
('花地瑪', 'FGS'),
('粤华中学', 'DBYW|stream'),
('濠江英才中學', 'HKMS-PS'),
('聖6', 'CDSJ6-E'),
('澳門嘉諾撒聖心中學', 'SHCC-C'),
('新华中學', '新華'),
('聖諾瑟3校', 'CDSJ3'),
('聖若瑟第二校英文部', 'CDSJ2-E'),
('srl english school f4', 'SRL-E'),
('澳門化地瑪聖母女子學校', 'FGS'),
('蔡高', 'CKS'),
('東南中學', 'TNS'),
('同善堂中学', '同善堂'),
('puiching middle school coloane campus', 'PCMS-CO'),
('澳大附中', 'ASUM'),
('聖羅撒英文部女子中學', 'SRL-E'),
('聖若瑟教區綜合第五校', 'CDSJ5-C'),
('聖羅撒英文中學（中四）', 'SRL-E'),
('school of the nation', 'SON'),
('聖若瑟第六校', 'CDSJ6|stream'),
('mac', 'MAC'),
('tns', 'TNS'),
('phc-c', 'PHC-C'),
('the international school of macao', 'TIS'),
('pui ching coloane', 'PCMS-CO'),
('澳門星聖羅撒女子中學中文部', 'SRL-C'),
('勞工子弟學校', 'LHS'),
('pooi to middle school', 'PTMS'),
('粵華英', 'DBYW-E'),
('濠江', 'HKMS'),
('現讀培正，升中三轉去tis', 'TIS'),
('cdsj6', 'CDSJ6-E'),
('聖心中文部', 'SHCC-C'),
('嶺南學校', '嶺南中學'),
('高美士', '高美士中葡'),
(',慈幼', 'IS'),
('聖羅撒英文學校', 'SRL-E'),
('鏡平', 'KPS'),
('santa rosa de lime english secondary school', 'SRL-E'),
('srl-c', 'SRL-C'),
('yuet wa', 'DBYW-C'),
('sacred heart canossian college', 'SHCC|stream'),
('聖若瑟敎區中學第五校', 'CDSJ5-E'),
('東南', 'TNS'),
('cskphc', 'PHC-E'),
('培正路環部', 'PCMS-CO'),
('鮑思高粵華小學六年級', 'DBYW-C'),
('澳門傳承國際學校', 'GIS'),
('教業中學（國際部）', 'KYIS'),
('中德學校', '中德'),
('培華學校', 'PVMS'),
('srl english', 'SRL-E'),
('聖羅撒英文女子中學', 'SRL-E'),
('聖若瑟中學（第六校）', 'CDSJ6-C'),
('srl中文部', 'SRL-C'),
('氹仔聖公會', 'MAC'),
('cdsj 2', 'CDSJ2-E'),
('坊眾', 'FCS'),
('浸信中學', '浸信'),
('pcms', 'PCMS'),
('kys', 'KYS'),
('put ching (coloane)', 'PCMS-CO'),
('菜農子弟', 'CNS'),
('嘉諾撒聖心女子中學', 'SHCC-E'),
('聖心學校', 'SHCC-C'),
('氹仔坊眾/可能轉路環培正', 'PCMS-CO'),
('聖若瑟教區中學中文部3校', 'CDSJ3'),
('氹仔坊眾', 'FCT'),
('聖若瑟六', 'CDSJ6-C'),
('rose', 'SRL-E'),
('教業中學(皇朝）', 'KYS'),
('陳瑞褀永援中學', 'PHC-E'),
('石排灣公立學校', '石排灣公立學校'),
('聖公會中學', 'MAC'),
('聖約瑟六校', 'CDSJ6-E'),
('升讀 粵華中學', 'DBYW-E'),
('濠江英才學校', 'HKMS-PS'),
('our lady of fatima girls school', 'FGS'),
('鮑小英', 'DBYW-E'),
('pui ching middle school (coloane)', 'PCMS-CO'),
('中葡職業技術學校', '中葡職中'),
('聖若瑟教區中學英文部', 'CDSJ?-E'),
('聖若瑟教區中學五校', 'CDSJ5-E'),
('鮑思高粵華小學英文部 升讀 聖心中學', 'SHCC-C'),
('劳校中学', 'LHS'),
('cdsj5-e', 'CDSJ5-E'),
('srl英', 'SRL-E'),
('澳大附屬應用學校', 'ASUM'),
('澳大附屬學校', 'ASUM'),
('培正中學 （路環校部）', 'PCMS-CO'),
('lhs', 'LHS'),
('聖家', '聖家'),
('粤華', 'DBYW-C'),
('聖若瑟中學第六校', 'CDSJ6-C'),
('傳𠄘國際', 'GIS'),
('pcmsco', 'PCMS-CO'),
('氹仔聖公會中學', 'MAC'),
('聖若瑟二校英文部', 'CDSJ2-E'),
('現讀澳門培正，將轉永援', 'PHC-E'),
('pvms', 'PVMS'),
('新华学校', '新華'),
('澳門培正國際部', 'PCMS-CO'),
('化地玛聖母女子學校', 'FGS'),
('cdsj5-c', 'CDSJ5-C'),
('cdsj6-c', 'CDSJ6-C'),
('庇道學校', '庇道'),
('氹坊', 'FCT'),
('澳門浸信中學', '浸信'),
('cdsj2-e', 'CDSJ2-E');
