// Auto-generated by scripts/parse-changelog.ts — do not edit manually
const changelogData = [
  {
    "version": "2.0.4",
    "date": "2026-02-15",
    "sections": [
      {
        "title": "New Features",
        "items": [
          {
            "description": "**Interactive geometry editor** — draw points, lines, segments, circles, polygons, function graphs, text labels, and angles on an interactive JSXGraph board; hexagon toolbar button in the inbox editor"
          },
          {
            "description": "**Geometry viewer** — click sent diagram thumbnails to open an interactive read-only viewer with zoom in/out/reset controls and drag-to-pan"
          },
          {
            "description": "**Function graphing** — plot mathematical functions via LaTeX input with MathLive virtual keyboard, converted to JS and rendered as curves on the geometry board"
          },
          {
            "description": "**Theme-reactive geometry boards** — boards re-render with correct colors when switching between light and dark mode"
          }
        ]
      },
      {
        "title": "Bug Fixes",
        "items": [
          {
            "description": "Fixed MathLive menu button requiring long press to open (scrim dismiss race condition)"
          },
          {
            "description": "Fixed matrix equations rendering with \"amp\" text in sent messages (HTML entity unescaping)"
          },
          {
            "description": "Fixed doubled axis tick labels in geometry viewer (skip auto-generated text during serialization)"
          },
          {
            "description": "Validated SVG data URIs before rendering geometry thumbnails"
          }
        ]
      }
    ]
  },
  {
    "version": "2.0.3",
    "date": "2026-02-15",
    "sections": [
      {
        "title": "New Features",
        "items": [
          {
            "description": "**Math equations in inbox** — type `$...$` for inline or `$$...$$` for block math, rendered with KaTeX; Sigma toolbar button converts selected text to equations; click to edit existing equations"
          },
          {
            "description": "**Math equation editor modal** — dedicated editor with MathLive mathfield and virtual keyboard for visual equation input; supports inline/block mode toggle with descriptions, edit/delete existing equations, and Ctrl/⌘+Enter shortcut to insert"
          },
          {
            "description": "**Themed virtual keyboard** — MathLive keyboard styled with warm brown palette matching app design, with full dark mode support"
          }
        ]
      },
      {
        "title": "Bug Fixes",
        "items": [
          {
            "description": "Fixed send button disabled when message contains only math equations"
          },
          {
            "description": "Fixed math equations vanishing from message bubbles on re-render"
          },
          {
            "description": "Fixed event listener leak in math editor modal (input handler never cleaned up)"
          },
          {
            "description": "Fixed focus not returning to message editor after closing math modal"
          },
          {
            "description": "Fixed mathfield border invisible in dark mode"
          }
        ]
      }
    ]
  },
  {
    "version": "2.0.2",
    "date": "2026-02-14",
    "sections": [
      {
        "title": "New Features",
        "items": [
          {
            "description": "**Chat-style thread view** — redesigned inbox thread detail with message bubbles, avatars, date separators, and typing indicators"
          },
          {
            "description": "**Scheduled send** — compose messages with schedule picker (preset times or custom datetime), inline edit before send, delivery timestamp updated on send"
          },
          {
            "description": "**@Mentions** — type `@` in the editor for autocomplete, mentions stored and surfaced in dedicated Mentions sidebar with unread badge and priority notifications that bypass thread mute"
          },
          {
            "description": "**Snooze** — snooze messages with preset or custom times, background task automatically marks as unread when snooze expires via SSE"
          },
          {
            "description": "**Voice messages** — record audio via microphone, upload to cloud storage, inline AudioPlayer with waveform visualization"
          },
          {
            "description": "**Message templates** — quick-insert reusable message templates from a picker"
          },
          {
            "description": "**Link previews** — automatic Open Graph previews for URLs in messages"
          },
          {
            "description": "**Emoji reactions** — react to messages with emoji, displayed as pills below message bubbles"
          }
        ]
      },
      {
        "title": "Improvements",
        "items": [
          {
            "description": "**Sidebar reorganization** — 3 sections: primary mailboxes, smart views (Starred, Mentions, Send Later, Snoozed), and collapsible Tags"
          },
          {
            "description": "**Rich interactions** — quote-reply, message forwarding, swipe actions, keyboard shortcuts"
          },
          {
            "description": "**Paste/drag image uploads** — parallel processing for multiple images"
          },
          {
            "description": "**Search highlighting** — across thread list and message content"
          },
          {
            "description": "**Draft auto-save** — with thread list preview indicator"
          },
          {
            "description": "**Dark mode polish** — across all new components"
          },
          {
            "description": "**Performance** — memoized components, stale-while-revalidate for category navigation"
          },
          {
            "description": "**Video & GIF attachments** — send and preview video/GIF files inline in messages"
          },
          {
            "description": "**Message forwarding with attachments** — forwarded messages now include all original attachments (images, files, voice recordings)"
          },
          {
            "description": "**Categorized attachment menu** — attachment button opens a popover with Photos & Videos / Document sections"
          },
          {
            "description": "**File attachments in replies** — attach files when replying, with thumbnail previews and remove button"
          },
          {
            "description": "**Portal-based popovers** — all toolbar dropdowns (emoji, color picker, attachments, templates) now render via portals, fixing overflow clipping on mobile and in edit mode"
          },
          {
            "description": "**Slide animations** — smooth expand/collapse on search filters panel and collapsible sections"
          }
        ]
      },
      {
        "title": "Bug Fixes",
        "items": [
          {
            "description": "Unread counts now exclude scheduled (unsent) messages"
          },
          {
            "description": "Fixed inbox loading skeleton getting stuck when navigating between categories"
          },
          {
            "description": "Fixed timezone mismatch in snooze reminder background task (use HK time consistently)"
          },
          {
            "description": "Added row-level locking to prevent duplicate scheduled message delivery"
          },
          {
            "description": "Added unique constraint on thread pins to prevent duplicates"
          },
          {
            "description": "Fixed voice message emoji rendering — replaced with Lucide Mic SVG icon"
          },
          {
            "description": "Fixed voice message duration not persisting in file_attachments metadata"
          },
          {
            "description": "Fixed duplicate tiptap Link extension warning in rich editors"
          },
          {
            "description": "Fixed changelog markdown rendering on What's New page"
          }
        ]
      }
    ]
  },
  {
    "version": "2.0.1",
    "date": "2026-02-13",
    "sections": [
      {
        "title": "New Features",
        "items": [
          {
            "description": "Group messaging — send messages to multiple specific tutors (not just one or all)"
          },
          {
            "description": "Multi-select recipient picker with tutor checkboxes and chip display"
          },
          {
            "description": "Group messages show \"Group (N)\" badge in thread list and green highlight in thread detail"
          },
          {
            "description": "Reply to group message inherits original recipients"
          }
        ]
      },
      {
        "title": "Improvements",
        "items": [
          {
            "description": "Message pinning/starring across all inbox views (inbox, archived, categories)"
          },
          {
            "description": "Inbox sidebar reorganized into Mailboxes and Categories sections"
          },
          {
            "description": "Draft auto-save for compose and reply forms"
          },
          {
            "description": "Batch \"Mark All Read\" for current category or entire inbox"
          }
        ]
      }
    ]
  },
  {
    "version": "2.0.0",
    "date": "2026-02-13",
    "sections": [
      {
        "title": "New Features",
        "items": [
          {
            "description": "Launch of CSM Pro web application — a complete rebuild from the original AppSheet v1.x"
          },
          {
            "description": "Dashboard with real-time stats, activity feed, and notification system"
          },
          {
            "description": "Session management with attendance tracking and make-up proposals"
          },
          {
            "description": "Student enrollment lifecycle with fee calculation and renewal tracking"
          },
          {
            "description": "Inbox messaging system with threads, search, and categories"
          },
          {
            "description": "Courseware library with usage analytics"
          },
          {
            "description": "Revenue reporting and overdue payment tracking"
          },
          {
            "description": "Exam revision slot management"
          },
          {
            "description": "Role-based access control (Super Admin, Admin, Supervisor, Tutor, Guest)"
          },
          {
            "description": "Command palette (Ctrl+K) for quick navigation"
          },
          {
            "description": "Dark mode support"
          }
        ]
      }
    ]
  }
] as const;

export default changelogData;
