// Auto-generated by scripts/parse-changelog.ts — do not edit manually
const changelogData = [
  {
    "version": "2.0.30",
    "date": "2026-03-12",
    "sections": [
      {
        "title": "Bug Fixes",
        "items": [
          {
            "description": "**Frontend version display** — fixed version number not updating in settings modal and \"What's New\" notifications"
          }
        ]
      },
      {
        "title": "Improvements",
        "items": [
          {
            "description": "**Code cleanup** — consolidated duplicate logic, hardcoded values, and repeated database query patterns across backend and frontend"
          },
          {
            "description": "**Batch operation performance** — batch mark-paid and mark-sent now load all enrollments in a single query instead of one per enrollment"
          },
          {
            "description": "**Exam revision performance** — batch-resolve makeup session chain lookups instead of querying one-by-one"
          },
          {
            "description": "**Zen mode performance** — memoized context providers to prevent unnecessary re-renders"
          },
          {
            "description": "**Renewal check performance** — batch-query renewal and schedule overlap lookups instead of per-enrollment queries"
          },
          {
            "description": "**Reduced unnecessary API calls** — disabled automatic refetch on window focus globally"
          },
          {
            "description": "**Accessibility** — added screen reader labels to icon buttons and dialog attributes to modals"
          },
          {
            "description": "**Dashboard & session list performance** — memoized attention card and proposed session components to reduce re-renders"
          },
          {
            "description": "**Test coverage 5x increase** — grew from ~134 to 646 tests (326 backend, 320 frontend) across 5 batches covering fee calculation, session scheduling, quarter boundaries, exam revision, rate limiting, HTML sanitization, SQL safety validation, revenue bonus tiers, LaTeX-to-JS conversion, makeup proposals, and 20+ utility modules"
          }
        ]
      }
    ]
  },
  {
    "version": "2.0.29",
    "date": "2026-03-12",
    "sections": [
      {
        "title": "New Features",
        "items": [
          {
            "description": "**Bulk exercise assignment in wide mode** — assign CW/HW to multiple students at once via student picker popover in the lesson wide mode sidebar (both by-student and by-file views)"
          },
          {
            "description": "**Clipboard paste in bulk modal** — exercises copied from ExerciseModal (Ctrl+C) can now be pasted into BulkExerciseModal (Ctrl+V) with confirmation dialog and source student info"
          },
          {
            "description": "**Multi-select bulk delete** — select multiple exercises via checkboxes and delete them all at once with an inline red confirmation banner; Alt+Backspace shortcut support"
          },
          {
            "description": "**PDF dark mode** — toggle button on all PDF viewers inverts page colors for comfortable dark reading; persisted via localStorage across PdfPageViewer, PdfPreviewModal, and Zen viewers"
          }
        ]
      },
      {
        "title": "Bug Fixes",
        "items": [
          {
            "description": "**Nested button hydration error** — fixed Next.js hydration warning caused by a print button nested inside the exercise item button in the lesson sidebar"
          }
        ]
      }
    ]
  },
  {
    "version": "2.0.28",
    "date": "2026-03-11",
    "sections": [
      {
        "title": "New Features",
        "items": [
          {
            "description": "**Select Attended sessions** — bulk-select attended sessions for CW/HW assignment and rating via new dropdown menus on both the sessions page and dashboard card; Ctrl+Shift+A now cycles through markable → attended → clear with toast feedback on each press"
          },
          {
            "description": "**Lesson mode print buttons** — single lesson mode now has bulk CW/HW print dropdown and per-exercise print buttons in sidebar; wide lesson mode adds per-student CW/HW print buttons in Students grouping"
          }
        ]
      },
      {
        "title": "Improvements",
        "items": [
          {
            "description": "**Toast feedback on selection** — all select actions (markable, attended, per-slot) now show info toasts with count or \"none found\" message instead of failing silently"
          },
          {
            "description": "**J/K navigation respects collapsed sections** — keyboard navigation now skips over collapsed time slot sections; Ctrl+A and Ctrl+Shift+A also only operate on visible (non-collapsed) sessions"
          }
        ]
      },
      {
        "title": "Bug Fixes",
        "items": [
          {
            "description": "**Student detail popover** — now shows all contact phone numbers with labels instead of only the single legacy phone field"
          }
        ]
      }
    ]
  },
  {
    "version": "2.0.27",
    "date": "2026-03-11",
    "sections": [
      {
        "title": "New Features",
        "items": [
          {
            "description": "**Bulk rate & comment** — rate and comment on multiple sessions at once from any timeslot header; copy timeslot info to clipboard"
          },
          {
            "description": "**Bulk exercise actions** — Print All, Download All, and Download Answers buttons on CW/HW section headers in both session detail and student courseware tab"
          },
          {
            "description": "**Courseware tab redesign** — consolidated layout with one card per session, CW/HW sub-grouping with colored accents, inline open/print buttons per exercise, and styled filter toggle"
          },
          {
            "description": "**Clickable test alerts** — upcoming assessment entries on the session detail page now link directly to the exam revision page"
          },
          {
            "description": "**Esc keyboard shortcut** — press Escape on session detail page to navigate back"
          }
        ]
      },
      {
        "title": "Improvements",
        "items": [
          {
            "description": "**Courseware tab readability** — darker text, opaque backgrounds, and StickyNote empty states for wooden desk theme in both courseware and tests tabs"
          },
          {
            "description": "**Print stamps on exercises** — open/print actions now include student info stamps"
          }
        ]
      },
      {
        "title": "Bug Fixes",
        "items": [
          {
            "description": "Fixed exams page back button always navigating to home instead of the actual previous page"
          },
          {
            "description": "Extracted shared `useBackNavigation` hook to consolidate duplicated history-aware back navigation"
          }
        ]
      }
    ]
  },
  {
    "version": "2.0.26",
    "date": "2026-03-11",
    "sections": [
      {
        "title": "New Features",
        "items": [
          {
            "description": "**Multiple contact numbers** — students can now have multiple phone numbers with relationship labels (Mother, Father, Grandparent, Student, Guardian, or custom free text); contacts are editable on the student detail page and add student modal"
          },
          {
            "description": "**Contact search** — search by any contact phone number across the student list, command palette, and duplicate detection"
          }
        ]
      },
      {
        "title": "Improvements",
        "items": [
          {
            "description": "**Contacts displayed everywhere** — enrollment detail modal, command palette preview, zen student page, and command palette subtitle all show full contact details with labels"
          }
        ]
      }
    ]
  },
  {
    "version": "2.0.25",
    "date": "2026-03-10",
    "sections": [
      {
        "title": "New Features",
        "items": [
          {
            "description": "**Haptic feedback** — tactile vibration on mobile for toasts, confirm dialogs, star ratings, action buttons, inbox reactions, voice recording, swipe gestures, and more via web-haptics with Android-optimized raw vibration patterns"
          },
          {
            "description": "**Tests & exams in command palette** — search tests and exams directly from the command palette with preview panel"
          },
          {
            "description": "**Feedback email notifications** — superadmin receives a Gmail email when tutors submit bug reports, feature requests, or suggestions via the feedback panel"
          }
        ]
      },
      {
        "title": "Improvements",
        "items": [
          {
            "description": "**Documents read-only for supervisors** — supervisors can view documents but cannot create, edit, delete, duplicate, lock, or manage folders; backend write endpoints return 403 for read-only roles"
          }
        ]
      },
      {
        "title": "Bug Fixes",
        "items": [
          {
            "description": "Fixed session cards jumping position when marking attendance (Attended/No Show now sort in place)"
          },
          {
            "description": "Fixed command palette recent searches saving on every keystroke instead of on selection"
          },
          {
            "description": "Fixed inbox emoji picker closing after every emoji selection — now stays open until you click away"
          },
          {
            "description": "Fixed unchecked attendance status column using plain gray pill instead of color-coded status tags"
          }
        ]
      }
    ]
  },
  {
    "version": "2.0.24",
    "date": "2026-03-10",
    "sections": [
      {
        "title": "New Features",
        "items": [
          {
            "description": "**GIF messaging** — search and send GIFs via GIPHY in inbox replies and compose, with trending browse and debounced search"
          },
          {
            "description": "**Supervisor broadcast inbox** — supervisors can now view broadcast messages in a read-only inbox (no compose, reply, react, or archive)"
          }
        ]
      },
      {
        "title": "Bug Fixes",
        "items": [
          {
            "description": "Fixed geometry editor undo/redo not respecting snap-to-grid setting"
          }
        ]
      }
    ]
  },
  {
    "version": "2.0.23",
    "date": "2026-03-10",
    "sections": [
      {
        "title": "Improvements",
        "items": [
          {
            "description": "**Eligible students based on slot locations** — eligible student count and list now reflect only the locations where revision slots exist, since cross-location revision is not allowed"
          },
          {
            "description": "**Discard warning on calendar event modal** — closing the event editor with unsaved changes now shows a confirmation prompt"
          }
        ]
      },
      {
        "title": "Bug Fixes",
        "items": [
          {
            "description": "Fixed voice messages showing 0:00 duration until played (WebM metadata workaround)"
          },
          {
            "description": "Fixed eligible students expanded list not matching collapsed count when \"All Locations\" is selected"
          },
          {
            "description": "Fixed exam-based eligible students endpoint not excluding already-enrolled students"
          }
        ]
      }
    ]
  },
  {
    "version": "2.0.22",
    "date": "2026-03-09",
    "sections": [
      {
        "title": "New Features",
        "items": [
          {
            "description": "**Zen inbox** — full inbox page in zen mode with thread viewing, media attachments, emoji reactions, and reply composer with file upload"
          },
          {
            "description": "**Unsaved annotation warning (lesson wide mode)** — exit confirmation dialog with \"Download All & Exit\" batch ZIP download, browser tab close warning, and `s` shortcut for saving current exercise"
          },
          {
            "description": "**Unsaved annotation warning (zen lesson mode)** — exit dialog now offers three options: Download All (ZIP), Download Current, and Exit; plus browser tab close warning"
          },
          {
            "description": "**Non-PDF fallback to Shelv** — local .doc/.docx files in lesson mode now fall through to Shelv search instead of failing"
          }
        ]
      },
      {
        "title": "Improvements",
        "items": [
          {
            "description": "Faster inbox refresh using background revalidation instead of full reload"
          }
        ]
      },
      {
        "title": "Bug Fixes",
        "items": [
          {
            "description": "Fixed annotated PDF download producing corrupted files in lesson wide mode"
          },
          {
            "description": "Fixed zen inbox always fetching messages for tutor ID 0 instead of actual user"
          },
          {
            "description": "Fixed `/` key being intercepted when typing in non-command-bar inputs"
          },
          {
            "description": "Fixed focused section not updating when inbox message is expanded"
          },
          {
            "description": "Fixed reaction button styling for own replies in zen inbox"
          }
        ]
      }
    ]
  },
  {
    "version": "2.0.21",
    "date": "2026-03-09",
    "sections": [
      {
        "title": "New Features",
        "items": [
          {
            "description": "**Web Push notifications** — receive OS-level notifications for new inbox messages even when the browser tab is closed, using free browser Push API with VAPID keys (no third-party service cost)"
          },
          {
            "description": "**Favicon unread badge** — red circle with unread message count overlaid on the browser tab icon, visible app-wide across all pages"
          },
          {
            "description": "**New message banner** — in-app toast showing sender name and preview when a message arrives for another thread, with click-to-jump and auto-dismiss"
          },
          {
            "description": "**Connection status indicator** — amber \"Reconnecting...\" or red \"Disconnected\" bar when the real-time SSE connection drops"
          },
          {
            "description": "**Differentiated urgent alerts** — urgent/high priority messages play a distinct two-tone sound and show red-accented notifications"
          }
        ]
      },
      {
        "title": "Improvements",
        "items": [
          {
            "description": "Dedicated 64x64 favicon for crisp display at small sizes"
          },
          {
            "description": "Inbox tab title shows unread count: `(3) Inbox - CSM Pro`"
          },
          {
            "description": "Push subscription auto-syncs once per browser session to recover from backend purges"
          }
        ]
      },
      {
        "title": "Bug Fixes",
        "items": [
          {
            "description": "Fixed zen annotation strokes disappearing after drawing"
          },
          {
            "description": "Fixed zen lesson PDF viewer race conditions during exercise switching"
          },
          {
            "description": "Fixed hi-res re-render overwriting pages on exercise switch"
          },
          {
            "description": "Fixed cached blob URL revocation causing broken images during student switch"
          },
          {
            "description": "Fixed zen exercise assign showing stale data when switching CW/HW or students"
          },
          {
            "description": "Fixed zen mode known issues: Escape handling, timer cleanup, and exit dialog"
          }
        ]
      }
    ]
  },
  {
    "version": "2.0.20",
    "date": "2026-03-08",
    "sections": [
      {
        "title": "New Features",
        "items": [
          {
            "description": "**Shared content panel in chat** — browse all media, files, links, audio, math, and graphs shared in a conversation thread with jump-to-message, sender filter, and tab navigation"
          },
          {
            "description": "**Chat quality-of-life** — message copy, reply banner, image zoom, loading skeleton, and accessibility improvements"
          },
          {
            "description": "**Zen lesson mode** — per-session and lesson-wide PDF viewing with keyboard-driven exercise navigation, page browsing, zoom, answer key toggle, open, and print"
          },
          {
            "description": "**Zen lesson mode exercise editing** — inline CW/HW assignment with pre-populated existing exercises, direct path input, search/browse, multi-select, and editable page ranges"
          },
          {
            "description": "**Zen lesson mode access everywhere** — `[L]esson` button on time slot headers and session detail panel across zen dashboard and sessions page. `L` opens single-student lesson mode, `Shift+L` opens lesson-wide mode"
          },
          {
            "description": "**Zen lesson-wide two-digit student keys** — student switcher supports numbers 1–99 with buffered input"
          },
          {
            "description": "**Zen courseware assign redesign** — tabbed date picker showing session details for clearer context when assigning exercises"
          }
        ]
      },
      {
        "title": "Improvements",
        "items": [
          {
            "description": "Shared lesson state hook eliminates duplication between single and wide lesson modes"
          },
          {
            "description": "Shared week date helpers deduplicated across pages"
          },
          {
            "description": "Dashboard session limit raised from 100 to 2000"
          }
        ]
      },
      {
        "title": "Bug Fixes",
        "items": [
          {
            "description": "Fixed PDF viewer crash during hi-res canvas re-render"
          },
          {
            "description": "Fixed trending courseware showing wrong relative time"
          },
          {
            "description": "Fixed checkbox column wrapping on zen sessions page"
          },
          {
            "description": "Fixed incoming message timestamp overlapping toolbar"
          },
          {
            "description": "Fixed reply-to-message linking broken by HTML sanitization stripping quote attributes"
          },
          {
            "description": "Fixed nested quote clutter in threaded replies"
          },
          {
            "description": "Fixed reply editor expanding beyond viewport"
          },
          {
            "description": "Fixed inbox thread pane UX issues with lightbox, scroll memory, and interactions"
          },
          {
            "description": "Fixed session_log debug writes failing on generated columns"
          }
        ]
      },
      {
        "title": "Known Issues",
        "items": [
          {
            "description": "**Lesson mode Escape handling** — when editing CW/HW exercises, pressing Escape may close the entire lesson mode instead of just the assignment panel"
          },
          {
            "description": "**Sessions page missing navigation shortcuts** — day view lacks shortcuts like `gg` (jump to first) that exist on the dashboard"
          },
          {
            "description": "**Session count ignores filters** — the completed/total count does not update when status or tutor filters are applied"
          },
          {
            "description": "**Filtered list navigation broken** — cursor up/down navigates the full list instead of only visible filtered sessions"
          },
          {
            "description": "**Lesson mode feature gaps** — annotation tools, bulk CW/HW download, and other main app lesson features are not yet available in zen lesson mode"
          }
        ]
      }
    ]
  },
  {
    "version": "2.0.19",
    "date": "2026-03-07",
    "sections": [
      {
        "title": "New Features",
        "items": [
          {
            "description": "**Zen courseware page** — new courseware tab in zen mode with browse, search, and assignment capabilities"
          },
          {
            "description": "**Zen trending podium** — redesigned zen courseware trending section as a medal ceremony podium with sparkle animation and stats labels"
          }
        ]
      },
      {
        "title": "Bug Fixes",
        "items": [
          {
            "description": "Fixed sending messages with geometry diagrams failing due to MySQL TEXT column size limit (64KB) — upgraded to MEDIUMTEXT (16MB)"
          },
          {
            "description": "Fixed PDF preview failing for students with Chinese names — stamp overlay now supports CJK characters"
          },
          {
            "description": "Fixed PDF preview occasionally showing \"Failed to process PDF\" despite the file being available — added auto-retry and better error handling"
          },
          {
            "description": "Fixed zen trending podium filename overflow and alignment across all columns"
          },
          {
            "description": "Fixed zen courseware page height causing site-level scrollbar"
          }
        ]
      }
    ]
  },
  {
    "version": "2.0.18",
    "date": "2026-03-06",
    "sections": [
      {
        "title": "New Features",
        "items": [
          {
            "description": "**Lesson-wide mode** — new multi-student lesson view accessible from the time slot header. Aggregates all students in a time slot into a single view with by-student and by-file sidebar modes, student switcher bar for shared exercises, per-exercise print buttons, and full annotation support"
          },
          {
            "description": "**Bulk print dropdown** — added CW/HW bulk print and download buttons to lesson-wide mode header for quick access"
          },
          {
            "description": "**Copy make-up message** — new \"Msg\" action button on make-up sessions generates a bilingual (中文/English) parent notification message with editable modal, language toggle, and one-tap copy. On mobile, copies directly to clipboard with visual feedback"
          },
          {
            "description": "**Dashboard lesson button** — added lesson-wide mode button to TodaySessionsCard time slot headers for quick access from the dashboard"
          }
        ]
      },
      {
        "title": "Bug Fixes",
        "items": [
          {
            "description": "Fixed bulk CW/HW download and print not inserting blank pages for double-sided printing — each student's pages now start on a new front page when printed duplex"
          },
          {
            "description": "Improved lesson mode header responsiveness on mobile — compact padding, smaller buttons, and floating sidebar toggle for lesson-wide mode"
          }
        ]
      }
    ]
  },
  {
    "version": "2.0.17",
    "date": "2026-03-06",
    "sections": [
      {
        "title": "New Features",
        "items": [
          {
            "description": "**Exercise history panel** — side panel in exercise modal showing past exercises for each student, with duplicate detection warnings when assigning previously-used exercises"
          },
          {
            "description": "**\"All\" proposals tab** — admin and super admin users can now see all proposals across tutors in the proposals view"
          },
          {
            "description": "**Proposals loading skeletons** — replaced spinner with shimmer skeleton cards matching the proposal card layout"
          },
          {
            "description": "**Document editor list improvements** — nested list style cycling (1→a→i for ordered, disc→circle→square for bullets), task/checklist support with toolbar button and `Ctrl+Shift+9` shortcut, arbitrary start number input rule (e.g. type `3. ` to start at 3), start number dropdown on toolbar, right-click context menu for ordered lists (restart numbering, set value, convert types), and plain text paste detection for list patterns"
          },
          {
            "description": "**Zen mode view toggle & impersonation** — added view mode toggle (My View/Center View) and role impersonation support to zen mode"
          }
        ]
      },
      {
        "title": "Bug Fixes",
        "items": [
          {
            "description": "Fixed sidebar view switching (My View → Center View) not updating the session page tutor filter on first click"
          },
          {
            "description": "Fixed \"For you\" badge incorrectly showing on proposals in the All tab when the admin is neither proposer nor target"
          },
          {
            "description": "Improved visual distinction between Book/Propose modes in makeup modal — color-coded toggle (green for Book, blue for Propose) with accent border"
          },
          {
            "description": "Fixed inbox showing message threads not belonging to the current user"
          },
          {
            "description": "Fixed leave record button always pointing to super admin's link instead of the current user's"
          },
          {
            "description": "Fixed zen mode column overflow with wider theme fonts"
          },
          {
            "description": "Removed confusing `!=alerts` hint from zen header"
          },
          {
            "description": "Restricted Add Student and New Enrollment buttons to admin users only"
          },
          {
            "description": "Fixed lesson mode answer viewer not respecting custom page ranges — now correctly handles complex page selections (e.g., \"1,3,5-7\")"
          },
          {
            "description": "Fixed lesson mode PDF viewer header showing \"p3-6\" instead of \"p3,6\" for non-contiguous pages"
          },
          {
            "description": "Fixed lesson mode PDF viewer \"Fit to width\" button using a fullscreen-style icon — now uses a horizontal expand icon that better conveys its purpose"
          },
          {
            "description": "Fixed sessions list time slot chevron icons using confusing tree-view convention — now uses standard accordion pattern (up=collapse, down=expand)"
          }
        ]
      }
    ]
  },
  {
    "version": "2.0.16",
    "date": "2026-03-06",
    "sections": [
      {
        "title": "New Features",
        "items": [
          {
            "description": "**Zen enrollments** — added inline enrollment detail within zen student view"
          },
          {
            "description": "**Zen student detail** — expanded to 7 tabs with full feature parity, copy lesson dates, and makeup proposal indicators"
          }
        ]
      },
      {
        "title": "Improvements",
        "items": [
          {
            "description": "Removed standalone zen enrollments page to match main app structure"
          }
        ]
      },
      {
        "title": "Bug Fixes",
        "items": [
          {
            "description": "Fixed profile pictures not saving — widened `profile_picture` column from VARCHAR(500) to VARCHAR(2048) to accommodate Google profile picture URLs"
          },
          {
            "description": "Fixed exercise modal not allowing deletion of all exercises of a type"
          },
          {
            "description": "Fixed emoji picker appearing beneath the feedback modal"
          },
          {
            "description": "Fixed makeup session appearing on wrong date in sessions list"
          },
          {
            "description": "Fixed document editor tab indents not deletable with Backspace — now reduces indent level instead of merging blocks"
          },
          {
            "description": "Fixed document editor numbered list auto-format being too aggressive — now only triggers on \"1. \" instead of any number"
          },
          {
            "description": "Fixed inability to cancel makeup sessions rescheduled to a different tutor — original tutor now also has cancel permission"
          }
        ]
      }
    ]
  },
  {
    "version": "2.0.15",
    "date": "2026-03-05",
    "sections": [
      {
        "title": "New Features",
        "items": [
          {
            "description": "**Zen mode pages** — added Students, Sessions, Revenue, and Courseware pages with full keyboard navigation"
          },
          {
            "description": "**Zen sessions week/day views** — redesigned with week summary + day detail layout, bulk-aware quick mark with confirmation dialog"
          },
          {
            "description": "**Shared zen components** — extracted ZenSpinner and ZenProgressBar for consistent loading states across all zen pages"
          }
        ]
      },
      {
        "title": "Improvements",
        "items": [
          {
            "description": "Deduplicated zen mark handlers, shared utilities, session sorting, date formatters, and enrollment utilities"
          },
          {
            "description": "Context-aware nav hints in zen session list (bulk vs default mode)"
          },
          {
            "description": "Standardized zen divider widths and empty state punctuation"
          },
          {
            "description": "Fixed zen header shortcut hints (Shift+T, Shift+P) and notification links"
          }
        ]
      },
      {
        "title": "Bug Fixes",
        "items": [
          {
            "description": "Fixed bulk confirm payment not decrementing student coupon count when enrollment has a coupon discount"
          },
          {
            "description": "Fixed renewals page bulk actions only processing the last selected item when items were selected across different search queries"
          },
          {
            "description": "Fixed zen revenue page infinite loading for admin center-view by including tutor loading state"
          },
          {
            "description": "Fixed zen activity feed cursor color and outline shift on focus"
          },
          {
            "description": "Fixed dashboard cards overflowing on narrow mobile screens"
          },
          {
            "description": "Fixed SWR server component build errors in sessionSorting and callMarkApi"
          }
        ]
      }
    ]
  },
  {
    "version": "2.0.14",
    "date": "2026-03-01",
    "sections": [
      {
        "title": "Bug Fixes",
        "items": [
          {
            "description": "Fixed student profile edits (name, phone, school, etc.) not saving"
          },
          {
            "description": "Fixed dashboard cards (Today's Sessions, Tests & Exams) overflowing horizontally on narrow screens"
          }
        ]
      }
    ]
  },
  {
    "version": "2.0.13",
    "date": "2026-02-27",
    "sections": [
      {
        "title": "New Features",
        "items": [
          {
            "description": "**Bulk Confirm Payment on overdue-payments page** — multi-select with checkboxes, section-level select all, and animated batch action bar with optimistic updates"
          },
          {
            "description": "**Implicit & parametric curves in geometry editor** — curve mode selector (f(x), f(x,y)=0, x(t),y(t)) with MathLive input, t-range controls, and full serialization for save/restore"
          },
          {
            "description": "**Click-to-edit plotted curves** — select any plotted curve to load its equation back into the input field; Update replaces the curve, Cancel returns to select mode"
          }
        ]
      },
      {
        "title": "Improvements",
        "items": [
          {
            "description": "Redesigned action button colors for better distinction: Undo (indigo), Extension (purple), Schedule Make-up (teal) — consistent across action buttons and chalkboard stubs"
          },
          {
            "description": "Moved unpaid badge from a separate pill to a compact inline icon next to the student name on sessions list and dashboard"
          },
          {
            "description": "Added within-cell sorting to monthly popover grid view for consistency with list view ordering"
          },
          {
            "description": "Added optimistic updates to renewals page bulk Confirm Payment and Mark Sent actions for instant UI feedback"
          }
        ]
      },
      {
        "title": "Bug Fixes",
        "items": [
          {
            "description": "Fixed unpaid red student name being overridden by strikethrough gray in Weekly, Daily, Monthly, and MoreSessionsPopover views"
          },
          {
            "description": "Fixed schedule make-up modal blocking slots that only contain cancelled sessions — conflict check now matches DB guard logic"
          },
          {
            "description": "Fixed monthly popover grid view missing unpaid red and strikethrough styling on student names"
          },
          {
            "description": "Fixed geometry editor modal footer (Insert/Cancel) pushed off-screen when function input bars are active — header and footer now pinned with scrollable middle section"
          }
        ]
      }
    ]
  },
  {
    "version": "2.0.12",
    "date": "2026-02-27",
    "sections": [
      {
        "title": "New Features",
        "items": [
          {
            "description": "**Custom date picker popover** — replaced native date inputs with a calendar popover across sessions list, weekly, and daily grid views for better month navigation without triggering date changes"
          },
          {
            "description": "**\"Active\" status filter** — new composite filter option that hides resolved sessions (Pending Make-up, Make-up Booked, Cancelled) in one click"
          },
          {
            "description": "**Button restyling** — action buttons and View/Lesson links now have borders and shadows to visually distinguish them from info badges"
          }
        ]
      },
      {
        "title": "Improvements",
        "items": [
          {
            "description": "Improved vertical data density in sessions list and calendar views"
          },
          {
            "description": "Push undo/cancel/edit action buttons to the right edge of session cards"
          },
          {
            "description": "Session count moved to badge on toolbar icon for a cleaner toolbar"
          },
          {
            "description": "De-emphasized resolved sessions with reduced opacity (Pending Make-up 0.8, Make-up Booked 0.6) while keeping action buttons at full opacity"
          },
          {
            "description": "Hidden CW/HW/Rate buttons and View/Lesson links on resolved session cards"
          },
          {
            "description": "Applied same action button cleanup to TodaySessionsCard on dashboard"
          },
          {
            "description": "Made sessions toolbar more compact on mobile"
          }
        ]
      },
      {
        "title": "Bug Fixes",
        "items": [
          {
            "description": "Fixed cancelled enrollment's deadline still being used for session extension — after cancelling the latest enrollment, the system now correctly falls back to the previous enrollment's deadline"
          },
          {
            "description": "Fixed unpaid red student name being overridden by strikethrough gray on rescheduled sessions"
          },
          {
            "description": "Fixed right-aligned action buttons breaking layout in SessionDetailPopover and on mobile"
          },
          {
            "description": "Fixed loading skeletons to match new sessions list layout"
          },
          {
            "description": "Fixed time slot headers left-aligned on mobile, centered on desktop"
          },
          {
            "description": "Fixed debug table horizontal scrollbar accessibility"
          }
        ]
      }
    ]
  },
  {
    "version": "2.0.11",
    "date": "2026-02-23",
    "sections": [
      {
        "title": "New Features",
        "items": [
          {
            "description": "**Geometry editor drag-to-pan** — middle-click or right-click drag to pan the board in any tool mode; two-finger touch pan on mobile devices"
          }
        ]
      },
      {
        "title": "Bug Fixes",
        "items": [
          {
            "description": "Fixed terminated students dropdown showing current/future quarters that aren't ready for review"
          },
          {
            "description": "Fixed documents page tab buttons overflowing on mobile"
          }
        ]
      }
    ]
  },
  {
    "version": "2.0.10",
    "date": "2026-02-22",
    "sections": [
      {
        "title": "New Features",
        "items": [
          {
            "description": "**Document preview pane** — toggle a side panel to preview documents without leaving the list; includes print buttons (Questions Only / With Answers) and keyboard shortcuts (Enter to open, Escape to close)"
          },
          {
            "description": "**My Docs & Recent tabs** — unified tab bar (All Docs | My Docs | Recent | Templates) replaces separate tabs and scope filters; My Docs shows documents you created or edited, Recent tracks documents you opened via localStorage"
          },
          {
            "description": "**Pending make-ups view** — urgency-tier grouping (Critical / Warning / OK / Overdue) with collapsible tiers, lazy-loading pagination, 2-state sort toggle, root original date display, schedule make-up button integration, and aged pending make-ups notification bell item"
          },
          {
            "description": "**Sort tiebreakers** — sessions with the same pending days now sort by location, then school student ID"
          }
        ]
      },
      {
        "title": "Performance",
        "items": [
          {
            "description": "Fixed infinite re-renders on pending-makeups view caused by Next.js 15 history patching and unstable context provider values"
          },
          {
            "description": "Memoized all context provider values (Auth, Location, Role, CommandPalette, Toast) and SWRConfig"
          },
          {
            "description": "Stabilized useActiveTutors hook, keyboard effect dependencies, and scroll handler"
          }
        ]
      },
      {
        "title": "Bug Fixes",
        "items": [
          {
            "description": "Fixed list view item backgrounds protruding past rounded container corners on mobile"
          }
        ]
      }
    ]
  },
  {
    "version": "2.0.9",
    "date": "2026-02-22",
    "sections": [
      {
        "title": "New Features",
        "items": [
          {
            "description": "**Editable templates** — create, edit, and delete document templates from the frontend"
          },
          {
            "description": "**Auto-delete empty docs** — untitled documents with no content are automatically deleted on exit; folder-scoped unique title enforcement"
          },
          {
            "description": "**Last editor tracking** — display who last edited a document, separate from the original author"
          }
        ]
      },
      {
        "title": "Improvements",
        "items": [
          {
            "description": "Template visual styling and metadata display"
          },
          {
            "description": "Document dropdown menus migrated to portal-based rendering for correct stacking"
          },
          {
            "description": "Archived documents now clickable with in-editor archived banner and Restore button"
          },
          {
            "description": "Footer pushed to page bottom on single-page documents"
          },
          {
            "description": "Sidebar transition smoothed when switching document/template tabs"
          },
          {
            "description": "Editor metadata moved inline with tags row on desktop"
          },
          {
            "description": "Table button repositioned in Insert toolbar"
          }
        ]
      },
      {
        "title": "Bug Fixes",
        "items": [
          {
            "description": "Fixed Delete key removing last empty paragraph (acting like Backspace)"
          },
          {
            "description": "Fixed single-page spacer jitter by using flex-grow layout"
          },
          {
            "description": "Fixed tiptap min-height causing oversized single pages"
          },
          {
            "description": "Fixed stale \"Load More\" button by deriving hasMore from data"
          },
          {
            "description": "Fixed TestCalendar upcoming section theme colors"
          }
        ]
      }
    ]
  },
  {
    "version": "2.0.8",
    "date": "2026-02-21",
    "sections": [
      {
        "title": "New Features",
        "items": [
          {
            "description": "**Version history** — side-by-side version diff with rich formatting, dynamic zoom, and layout comparison"
          },
          {
            "description": "**Pagination architecture** — migrated from Widget Decorations to Node Decorations + React overlay for stable page division, headers, footers, and watermarks"
          }
        ]
      },
      {
        "title": "Improvements",
        "items": [
          {
            "description": "Mobile responsiveness and UX polish for document list"
          },
          {
            "description": "Simplified document list with shared utilities"
          },
          {
            "description": "Location dropdown styling in settings modal"
          }
        ]
      },
      {
        "title": "Bug Fixes",
        "items": [
          {
            "description": "Fixed code blocks printing with dark background — now uses light theme with print-safe syntax highlighting in all editor modes"
          },
          {
            "description": "Fixed sidebar scroll shadows scrolling away instead of staying pinned"
          },
          {
            "description": "Fixed page chrome overlay alignment — footer/header/gap overlays now correctly offset for CSS padding-box origin"
          }
        ]
      }
    ]
  },
  {
    "version": "2.0.7",
    "date": "2026-02-21",
    "sections": [
      {
        "title": "New Features",
        "items": [
          {
            "description": "**Tags & folders** — organize documents with color-coded tags and a nested folder sidebar; tag search popover and inline editor tag dropdown"
          },
          {
            "description": "**Table enhancements** — column resize, cell background color picker, and merge/split cells"
          },
          {
            "description": "**Line spacing** — configurable line spacing for paragraphs and headings (1.0–3.0)"
          },
          {
            "description": "**Page count** — status bar shows total pages when document has more than one page"
          },
          {
            "description": "**{total} placeholder** — use `{total}` in headers/footers for \"Page 1 of 3\" style numbering"
          },
          {
            "description": "**Justify alignment** — fourth text alignment option in toolbar and bubble menu"
          },
          {
            "description": "**Link popover** — inline popover for inserting and editing links (replaces browser prompt)"
          },
          {
            "description": "**Code blocks** — supported in document editor"
          },
          {
            "description": "**8×8 table grid** — expanded table size picker for larger tables"
          }
        ]
      },
      {
        "title": "Improvements",
        "items": [
          {
            "description": "Document list pagination with sort controls and grid/list view toggle"
          },
          {
            "description": "Image upload validation on document list"
          },
          {
            "description": "Pagination footer stays at page bottom while typing; scroll position stable during page recalculation"
          },
          {
            "description": "Backgrounds and colors print correctly; isolated lines avoided at page breaks"
          },
          {
            "description": "Context menu accessible on mobile without hover"
          },
          {
            "description": "Search on document list debounced for smoother typing; clear button added"
          },
          {
            "description": "Empty state message adapts to active filters"
          },
          {
            "description": "Keyboard shortcuts modal includes math and code block shortcuts"
          },
          {
            "description": "Student coupon badge shows last-updated date on hover"
          }
        ]
      },
      {
        "title": "Bug Fixes",
        "items": [
          {
            "description": "Fixed document list theme contrast — missing dark mode variants on action buttons, low-contrast grey text against warm desk surface, and semi-transparent backgrounds letting desk texture bleed through"
          },
          {
            "description": "Fixed mobile list view doc type icon not showing dark mode color"
          },
          {
            "description": "Fixed archived document border style not rendering (invalid Tailwind class)"
          },
          {
            "description": "Fixed context menus not closing on outside click"
          },
          {
            "description": "Fixed Ctrl+S always triggers save for visual feedback"
          },
          {
            "description": "Fixed answer section hover colors in dark paper mode"
          },
          {
            "description": "Fixed staff referral checkbox not saving"
          }
        ]
      }
    ]
  },
  {
    "version": "2.0.6",
    "date": "2026-02-20",
    "sections": [
      {
        "title": "New Features",
        "items": [
          {
            "description": "**Document Builder** — full A4 document editor with TipTap: rich text formatting, tables with grid picker, resizable images with alignment/text wrapping, math equations (KaTeX), and geometry diagrams (JSXGraph)"
          },
          {
            "description": "**Page layout settings** — configurable margins, headers/footers with text templates ({title}, {page}, {date}), image logos, and separate English/Chinese font selection"
          },
          {
            "description": "**Pagination system** — accurate page break calculation with visual page gaps, headers/footers rendered in decorations, and zoom-independent measurement"
          },
          {
            "description": "**Print support** — browser-native print with correct page breaks, headers, footers, and watermarks; \"Questions Only\" and \"With Answers\" print modes"
          },
          {
            "description": "**Answer Key section** — floating, collapsible answer overlay with drag-to-reposition and per-question labeling"
          },
          {
            "description": "**Find & Replace** — search with highlight decorations, navigate between matches, replace current or all occurrences"
          },
          {
            "description": "**Keyboard shortcuts modal** — categorized reference for all editor shortcuts (Ctrl+/)"
          },
          {
            "description": "**Zoom controls** — zoom in/out with fit-to-width default on mobile; page breaks remain accurate at any zoom level"
          },
          {
            "description": "**Paper mode** — document always displays in light/print colors regardless of global dark mode, with toggle in status bar"
          },
          {
            "description": "**Document management** — create, duplicate, archive, restore, and permanently delete documents; mobile-responsive list view"
          },
          {
            "description": "**Document templates** — create documents from templates (e.g. MathConcept) with pre-configured margins, footer, watermark, and body font"
          },
          {
            "description": "**Body font settings** — new Fonts tab in Page Layout modal to set default font family (English + CJK) and font size for the document"
          },
          {
            "description": "**Block indent/outdent** — Tab/Shift+Tab to indent or outdent paragraphs and headings (up to 8 levels); toolbar buttons in Format tab"
          }
        ]
      },
      {
        "title": "Improvements",
        "items": [
          {
            "description": "Resizable media nodes support drag handles, alignment (left/center/right), and text wrapping"
          },
          {
            "description": "Tabbed toolbar layout with search and keyboard shortcuts buttons"
          },
          {
            "description": "Bubble menu for inline formatting on text selection"
          },
          {
            "description": "Explicit page break nodes insertable from toolbar"
          },
          {
            "description": "Documents section in sidebar with Beta badge"
          },
          {
            "description": "Toolbar font and size dropdowns reactively reflect the cursor-selected text style"
          }
        ]
      },
      {
        "title": "Bug Fixes",
        "items": [
          {
            "description": "Fixed watermark only appearing on first page in editor view"
          },
          {
            "description": "Fixed decoration watermark greyish overlay in light mode and white pixels in dark mode"
          }
        ]
      }
    ]
  },
  {
    "version": "2.0.5",
    "date": "2026-02-16",
    "sections": [
      {
        "title": "New Features",
        "items": [
          {
            "description": "**Code blocks with syntax highlighting** — toggle via toolbar button or type ``` in the editor; ~35 common languages auto-detected with Catppuccin Mocha color theme; highlighting preserved in sent messages"
          },
          {
            "description": "**Drag-and-drop attachment reordering** — drag images horizontally or files vertically (with grip handle) to reorder before sending, in both reply composer and compose modal"
          }
        ]
      },
      {
        "title": "Improvements",
        "items": [
          {
            "description": "Scheduled messages now deliver reliably via background task even if the sender doesn't reopen their inbox"
          },
          {
            "description": "Math editor templates insert at cursor position instead of replacing the entire equation"
          },
          {
            "description": "Snoozed and scheduled message lists load faster with batched queries"
          }
        ]
      },
      {
        "title": "Bug Fixes",
        "items": [
          {
            "description": "Fixed segment measurement labels not updating color when switching between light and dark mode"
          },
          {
            "description": "Fixed measurement label colors reverting to stale values on undo/redo"
          }
        ]
      }
    ]
  },
  {
    "version": "2.0.4",
    "date": "2026-02-15",
    "sections": [
      {
        "title": "New Features",
        "items": [
          {
            "description": "**Interactive geometry editor** — draw points, lines, segments, circles, polygons, function graphs, text labels, and angles on an interactive JSXGraph board; hexagon toolbar button in the inbox editor"
          },
          {
            "description": "**Geometry viewer** — click sent diagram thumbnails to open an interactive read-only viewer with zoom in/out/reset controls and drag-to-pan"
          },
          {
            "description": "**Function graphing** — plot mathematical functions via LaTeX input with MathLive virtual keyboard, converted to JS and rendered as curves on the geometry board"
          },
          {
            "description": "**Theme-reactive geometry boards** — boards re-render with correct colors when switching between light and dark mode"
          },
          {
            "description": "**Grid snapping** — toggle snap-to-grid in the geometry editor toolbar (on by default) for precise point placement at integer coordinates"
          },
          {
            "description": "**Auto-named points** — points are automatically labeled A, B, C, ...; click a point in select mode to rename it"
          },
          {
            "description": "**Touch support** — geometry editor and viewer optimized for touch devices with larger hit targets and no browser gesture interference"
          },
          {
            "description": "**Area-select & group movement** — drag a selection rectangle over compound elements (angles, polygons, circles, segments) then drag any defining point to move the entire shape as a unit"
          },
          {
            "description": "**Polygon interior dragging** — click inside any polygon to drag it by its interior"
          },
          {
            "description": "**Exact angle input** — type a degree value in the text field when placing an angle to auto-compute the third point at the exact angle"
          }
        ]
      },
      {
        "title": "Improvements",
        "items": [
          {
            "description": "Snap-to-grid toggle now updates all existing points on the board"
          },
          {
            "description": "Theme toggle updates geometry board colors smoothly without visible flash"
          }
        ]
      },
      {
        "title": "Bug Fixes",
        "items": [
          {
            "description": "Fixed MathLive menu button requiring long press to open"
          },
          {
            "description": "Fixed matrix equations showing \"amp\" text in sent messages"
          },
          {
            "description": "Fixed doubled axis tick labels in geometry viewer"
          },
          {
            "description": "Fixed invalid geometry thumbnails not rendering"
          }
        ]
      }
    ]
  },
  {
    "version": "2.0.3",
    "date": "2026-02-15",
    "sections": [
      {
        "title": "New Features",
        "items": [
          {
            "description": "**Math equations in inbox** — type `$...$` for inline or `$$...$$` for block math, rendered with KaTeX; Sigma toolbar button converts selected text to equations; click to edit existing equations"
          },
          {
            "description": "**Math equation editor modal** — dedicated editor with MathLive mathfield and virtual keyboard for visual equation input; supports inline/block mode toggle with descriptions, edit/delete existing equations, and Ctrl/⌘+Enter shortcut to insert"
          },
          {
            "description": "**Themed virtual keyboard** — MathLive keyboard styled with warm brown palette matching app design, with full dark mode support"
          }
        ]
      },
      {
        "title": "Bug Fixes",
        "items": [
          {
            "description": "Fixed send button disabled when message contains only math equations"
          },
          {
            "description": "Fixed math equations disappearing from message bubbles"
          },
          {
            "description": "Fixed memory leak in math editor modal"
          },
          {
            "description": "Fixed focus not returning to message editor after closing math modal"
          },
          {
            "description": "Fixed math input border invisible in dark mode"
          }
        ]
      }
    ]
  },
  {
    "version": "2.0.2",
    "date": "2026-02-14",
    "sections": [
      {
        "title": "New Features",
        "items": [
          {
            "description": "**Chat-style thread view** — redesigned inbox thread detail with message bubbles, avatars, date separators, and typing indicators"
          },
          {
            "description": "**Scheduled send** — compose messages with schedule picker (preset times or custom datetime), inline edit before send, delivery timestamp updated on send"
          },
          {
            "description": "**@Mentions** — type `@` in the editor for autocomplete, mentions stored and surfaced in dedicated Mentions sidebar with unread badge and priority notifications that bypass thread mute"
          },
          {
            "description": "**Snooze** — snooze messages with preset or custom times, background task automatically marks as unread when snooze expires via SSE"
          },
          {
            "description": "**Voice messages** — record audio via microphone, upload to cloud storage, inline AudioPlayer with waveform visualization"
          },
          {
            "description": "**Message templates** — quick-insert reusable message templates from a picker"
          },
          {
            "description": "**Link previews** — automatic Open Graph previews for URLs in messages"
          },
          {
            "description": "**Emoji reactions** — react to messages with emoji, displayed as pills below message bubbles"
          }
        ]
      },
      {
        "title": "Improvements",
        "items": [
          {
            "description": "**Sidebar reorganization** — 3 sections: primary mailboxes, smart views (Starred, Mentions, Send Later, Snoozed), and collapsible Tags"
          },
          {
            "description": "**Rich interactions** — quote-reply, message forwarding, swipe actions, keyboard shortcuts"
          },
          {
            "description": "**Paste/drag image uploads** — supports multiple images at once"
          },
          {
            "description": "**Search highlighting** — across thread list and message content"
          },
          {
            "description": "**Draft auto-save** — with thread list preview indicator"
          },
          {
            "description": "**Dark mode polish** — across all new components"
          },
          {
            "description": "**Performance** — faster navigation and smoother category switching"
          },
          {
            "description": "**Video & GIF attachments** — send and preview video/GIF files inline in messages"
          },
          {
            "description": "**Message forwarding with attachments** — forwarded messages now include all original attachments (images, files, voice recordings)"
          },
          {
            "description": "**Categorized attachment menu** — attachment button opens a popover with Photos & Videos / Document sections"
          },
          {
            "description": "**File attachments in replies** — attach files when replying, with thumbnail previews and remove button"
          },
          {
            "description": "**Improved toolbar dropdowns** — emoji, color picker, attachments, and template menus no longer get clipped on mobile or in edit mode"
          },
          {
            "description": "**Slide animations** — smooth expand/collapse on search filters panel and collapsible sections"
          }
        ]
      },
      {
        "title": "Bug Fixes",
        "items": [
          {
            "description": "Unread counts now exclude scheduled (unsent) messages"
          },
          {
            "description": "Fixed inbox loading indicator getting stuck when switching categories"
          },
          {
            "description": "Fixed snooze reminders firing at wrong times due to timezone mismatch"
          },
          {
            "description": "Fixed scheduled messages occasionally being sent twice"
          },
          {
            "description": "Fixed threads sometimes getting pinned twice"
          },
          {
            "description": "Fixed voice message icon not displaying correctly"
          },
          {
            "description": "Fixed voice message duration not saving correctly"
          },
          {
            "description": "Fixed console warning in rich text editor"
          },
          {
            "description": "Fixed changelog markdown rendering on What's New page"
          }
        ]
      }
    ]
  },
  {
    "version": "2.0.1",
    "date": "2026-02-13",
    "sections": [
      {
        "title": "New Features",
        "items": [
          {
            "description": "Group messaging — send messages to multiple specific tutors (not just one or all)"
          },
          {
            "description": "Multi-select recipient picker with tutor checkboxes and chip display"
          },
          {
            "description": "Group messages show \"Group (N)\" badge in thread list and green highlight in thread detail"
          },
          {
            "description": "Reply to group message inherits original recipients"
          }
        ]
      },
      {
        "title": "Improvements",
        "items": [
          {
            "description": "Message pinning/starring across all inbox views (inbox, archived, categories)"
          },
          {
            "description": "Inbox sidebar reorganized into Mailboxes and Categories sections"
          },
          {
            "description": "Draft auto-save for compose and reply forms"
          },
          {
            "description": "Batch \"Mark All Read\" for current category or entire inbox"
          }
        ]
      }
    ]
  },
  {
    "version": "2.0.0",
    "date": "2026-02-13",
    "sections": [
      {
        "title": "New Features",
        "items": [
          {
            "description": "Launch of CSM Pro web application — a complete rebuild from the original AppSheet v1.x"
          },
          {
            "description": "Dashboard with real-time stats, activity feed, and notification system"
          },
          {
            "description": "Session management with attendance tracking and make-up proposals"
          },
          {
            "description": "Student enrollment lifecycle with fee calculation and renewal tracking"
          },
          {
            "description": "Inbox messaging system with threads, search, and categories"
          },
          {
            "description": "Courseware library with usage analytics"
          },
          {
            "description": "Revenue reporting and overdue payment tracking"
          },
          {
            "description": "Exam revision slot management"
          },
          {
            "description": "Role-based access control (Super Admin, Admin, Supervisor, Tutor, Guest)"
          },
          {
            "description": "Command palette (Ctrl+K) for quick navigation"
          },
          {
            "description": "Dark mode support"
          }
        ]
      }
    ]
  }
] as const;

export default changelogData;
