// Auto-generated by scripts/parse-changelog.ts — do not edit manually
const changelogData = [
  {
    "version": "2.0.2",
    "date": "2026-02-14",
    "sections": [
      {
        "title": "New Features",
        "items": [
          {
            "description": "**Chat-style thread view** — redesigned inbox thread detail with message bubbles, avatars, date separators, and typing indicators"
          },
          {
            "description": "**Scheduled send** — compose messages with schedule picker (preset times or custom datetime), inline edit before send, delivery timestamp updated on send"
          },
          {
            "description": "**@Mentions** — type `@` in the editor for autocomplete, mentions stored and surfaced in dedicated Mentions sidebar with unread badge and priority notifications that bypass thread mute"
          },
          {
            "description": "**Snooze** — snooze messages with preset or custom times, background task automatically marks as unread when snooze expires via SSE"
          },
          {
            "description": "**Voice messages** — record audio via microphone, upload to cloud storage, inline AudioPlayer with waveform visualization"
          },
          {
            "description": "**Message templates** — quick-insert reusable message templates from a picker"
          },
          {
            "description": "**Link previews** — automatic Open Graph previews for URLs in messages"
          },
          {
            "description": "**Emoji reactions** — react to messages with emoji, displayed as pills below message bubbles"
          }
        ]
      },
      {
        "title": "Improvements",
        "items": [
          {
            "description": "Sidebar reorganized into 3 sections: primary mailboxes, smart views (Starred, Mentions, Send Later, Snoozed), and collapsible Tags"
          },
          {
            "description": "Rich interactions: quote-reply, message forwarding, swipe actions, keyboard shortcuts"
          },
          {
            "description": "Paste/drag image uploads with parallel processing"
          },
          {
            "description": "Search highlighting across thread list and message content"
          },
          {
            "description": "Draft auto-save with thread list preview indicator"
          },
          {
            "description": "Dark mode polish across all new components"
          },
          {
            "description": "Performance: memoized components, stale-while-revalidate for category navigation"
          }
        ]
      },
      {
        "title": "Bug Fixes",
        "items": [
          {
            "description": "Unread counts now exclude scheduled (unsent) messages"
          },
          {
            "description": "Fixed inbox loading skeleton getting stuck when navigating between categories"
          },
          {
            "description": "Fixed timezone mismatch in snooze reminder background task (use HK time consistently)"
          },
          {
            "description": "Added row-level locking to prevent duplicate scheduled message delivery"
          },
          {
            "description": "Added unique constraint on thread pins to prevent duplicates"
          }
        ]
      }
    ]
  },
  {
    "version": "2.0.1",
    "date": "2026-02-13",
    "sections": [
      {
        "title": "New Features",
        "items": [
          {
            "description": "Group messaging — send messages to multiple specific tutors (not just one or all)"
          },
          {
            "description": "Multi-select recipient picker with tutor checkboxes and chip display"
          },
          {
            "description": "Group messages show \"Group (N)\" badge in thread list and green highlight in thread detail"
          },
          {
            "description": "Reply to group message inherits original recipients"
          }
        ]
      },
      {
        "title": "Improvements",
        "items": [
          {
            "description": "Message pinning/starring across all inbox views (inbox, archived, categories)"
          },
          {
            "description": "Inbox sidebar reorganized into Mailboxes and Categories sections"
          },
          {
            "description": "Draft auto-save for compose and reply forms"
          },
          {
            "description": "Batch \"Mark All Read\" for current category or entire inbox"
          }
        ]
      }
    ]
  },
  {
    "version": "2.0.0",
    "date": "2026-02-13",
    "sections": [
      {
        "title": "New Features",
        "items": [
          {
            "description": "Launch of CSM Pro web application — a complete rebuild from the original AppSheet v1.x"
          },
          {
            "description": "Dashboard with real-time stats, activity feed, and notification system"
          },
          {
            "description": "Session management with attendance tracking and make-up proposals"
          },
          {
            "description": "Student enrollment lifecycle with fee calculation and renewal tracking"
          },
          {
            "description": "Inbox messaging system with threads, search, and categories"
          },
          {
            "description": "Courseware library with usage analytics"
          },
          {
            "description": "Revenue reporting and overdue payment tracking"
          },
          {
            "description": "Exam revision slot management"
          },
          {
            "description": "Role-based access control (Super Admin, Admin, Supervisor, Tutor, Guest)"
          },
          {
            "description": "Command palette (Ctrl+K) for quick navigation"
          },
          {
            "description": "Dark mode support"
          }
        ]
      }
    ]
  }
] as const;

export default changelogData;
